/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cashOnDelivery' : IDL.Null,
  'card' : IDL.Null,
});
export const DiscountType = IDL.Variant({
  'percentage' : IDL.Null,
  'fixedAmount' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : IDL.Principal,
  'orderId' : IDL.Nat,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const PromoCode = IDL.Record({
  'discountValue' : IDL.Nat,
  'expiresAt' : Time,
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'minOrderValue' : IDL.Nat,
  'usageLimit' : IDL.Nat,
  'timesUsed' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const DeliverySettings = IDL.Record({
  'deliveryFee' : IDL.Nat,
  'freeDelivery' : IDL.Bool,
  'freeDeliveryThreshold' : IDL.Nat,
});
export const Offer = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : Time,
  'createdAt' : Time,
  'description' : IDL.Text,
  'discountPercentage' : IDL.Nat,
  'startDate' : Time,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'discount' : IDL.Opt(IDL.Nat),
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'applyPromoCode' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createOffer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Time, Time],
      [IDL.Nat],
      [],
    ),
  'createPayment' : IDL.Func([IDL.Nat, IDL.Nat, PaymentMethod], [IDL.Nat], []),
  'createProductDiscount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createPromoCode' : IDL.Func(
      [IDL.Text, DiscountType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int],
      [],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteOffer' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deletePromoCode' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getDeliverySettings' : IDL.Func([], [DeliverySettings], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getOrdersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Text, PaymentMethod],
      [IDL.Opt(Order)],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateDeliverySettings' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'upsertUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cashOnDelivery' : IDL.Null,
    'card' : IDL.Null,
  });
  const DiscountType = IDL.Variant({
    'percentage' : IDL.Null,
    'fixedAmount' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'userId' : IDL.Principal,
    'orderId' : IDL.Nat,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const PromoCode = IDL.Record({
    'discountValue' : IDL.Nat,
    'expiresAt' : Time,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'minOrderValue' : IDL.Nat,
    'usageLimit' : IDL.Nat,
    'timesUsed' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const DeliverySettings = IDL.Record({
    'deliveryFee' : IDL.Nat,
    'freeDelivery' : IDL.Bool,
    'freeDeliveryThreshold' : IDL.Nat,
  });
  const Offer = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : Time,
    'createdAt' : Time,
    'description' : IDL.Text,
    'discountPercentage' : IDL.Nat,
    'startDate' : Time,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'discount' : IDL.Opt(IDL.Nat),
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'applyPromoCode' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createOffer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Time, Time],
        [IDL.Nat],
        [],
      ),
    'createPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, PaymentMethod],
        [IDL.Nat],
        [],
      ),
    'createProductDiscount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createPromoCode' : IDL.Func(
        [IDL.Text, DiscountType, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Int],
        [],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteOffer' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deletePromoCode' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getDeliverySettings' : IDL.Func([], [DeliverySettings], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getOrdersByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Text, PaymentMethod],
        [IDL.Opt(Order)],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateDeliverySettings' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Bool], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, PaymentStatus], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'upsertUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };