/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface DeliverySettings {
  'deliveryFee' : bigint,
  'freeDelivery' : boolean,
  'freeDeliveryThreshold' : bigint,
}
export type DiscountType = { 'percentage' : null } |
  { 'fixedAmount' : null };
export interface Offer {
  'id' : bigint,
  'title' : string,
  'endDate' : Time,
  'createdAt' : Time,
  'description' : string,
  'discountPercentage' : bigint,
  'startDate' : Time,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'createdAt' : Time,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Payment {
  'id' : bigint,
  'status' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'userId' : Principal,
  'orderId' : bigint,
  'timestamp' : Time,
  'amount' : bigint,
}
export type PaymentMethod = { 'upi' : null } |
  { 'cashOnDelivery' : null } |
  { 'card' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface Product {
  'id' : bigint,
  'categoryId' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'discount' : [] | [bigint],
  'price' : bigint,
}
export interface PromoCode {
  'discountValue' : bigint,
  'expiresAt' : Time,
  'code' : string,
  'discountType' : DiscountType,
  'minOrderValue' : bigint,
  'usageLimit' : bigint,
  'timesUsed' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, bigint, bigint, string, boolean],
    bigint
  >,
  'applyPromoCode' : ActorMethod<[string, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], bigint>,
  'createOffer' : ActorMethod<[string, string, bigint, Time, Time], bigint>,
  'createPayment' : ActorMethod<[bigint, bigint, PaymentMethod], bigint>,
  'createProductDiscount' : ActorMethod<[bigint, bigint], undefined>,
  'createPromoCode' : ActorMethod<
    [string, DiscountType, bigint, bigint, bigint, bigint],
    undefined
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteOffer' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deletePromoCode' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllPromoCodes' : ActorMethod<[], Array<PromoCode>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getDeliverySettings' : ActorMethod<[], DeliverySettings>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyPayments' : ActorMethod<[], Array<Payment>>,
  'getOffers' : ActorMethod<[], Array<Offer>>,
  'getOrdersByUser' : ActorMethod<[Principal], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[bigint], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, string, PaymentMethod],
    [] | [Order]
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[bigint, string, string], undefined>,
  'updateDeliverySettings' : ActorMethod<[bigint, bigint, boolean], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updatePaymentStatus' : ActorMethod<[bigint, PaymentStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, bigint, string, boolean],
    undefined
  >,
  'upsertUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];